@id = fc87c98d-3c59-4e50-9e03-74ade5e25ea4

POST http://localhost:5000/car
Content-Type: application/json

{
  "brand": "BMW",
  "model": "X5",
  "color": "black",

  "year": 2019,
  "type": "SUV",

  "image": "url.jpg"
}

###

GET http://localhost:5000/car/{{id}}

###

PUT http://localhost:5000/car/{{id}}
Content-Type: application/json

{
  "brand": "BMW",
  "model": "X5",
  "color": "black",

  "year": 2020,
  "type": "SUV",

  "image": "url.jpg"
}

###

DELETE http://localhost:5000/car/{{id}}

###
